# Run unit tests on any branch/fork pull request
on:
  pull_request

name: Unit tests

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:

    # <insert integration tests needing secrets>

    - run: echo "Unit tests... success! ;-)"

    - name: GitHub App token
      id: generate_token_test
      uses: tibdex/github-app-token@v1.0.2
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.PRIVATE_KEY }}
